export const DOC_LIST_REQUEST = "DOC_LIST_REQUEST";
export const DOC_LIST_SUCCESS = "DOC_LIST_SUCCESS";
export const DOC_LIST_FAIL    = "DOC_LIST_FAIL";

export const DOC_CREATE_REQUEST = "DOC_CREATE_REQUEST";
export const DOC_CREATE_SUCCESS = "DOC_CREATE_SUCCESS";
export const DOC_CREATE_FAIL    = "DOC_CREATE_FAIL";

export const DOC_UPDATE_REQUEST = "DOC_UPDATE_REQUEST";
export const DOC_UPDATE_SUCCESS = "DOC_UPDATE_SUCCESS";
export const DOC_UPDATE_FAIL    = "DOC_UPDATE_FAIL";

export const DOC_DELETE_REQUEST = "DOC_DELETE_REQUEST";
export const DOC_DELETE_SUCCESS = "DOC_DELETE_SUCCESS";
export const DOC_DELETE_FAIL    = "DOC_DELETE_FAIL";




